### ISSUE TITLE
idk what this is tbh

### ISSUE THREAD

**Issue by elmolaygo** [FireRedz/osr2png#13]
[Version] Current version: 0.7.5
[Version] Checking github for a new version of osr2png, success!
[Version] You're using an older version of osr2png.
[Version] You can update it from here: https://github.com/xjunko/osr2png/releases/tag/0.8.1
[Replay2Picture] File: `Alphi- - THE ORAL CIGARETTES - ReI [Shunao's Hard] (2024-11-27) Osu.osr`
[Replay] Replay loaded!
[Replay2Picture] No Beatmap file passed, getting from osu!
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 163, in <module>
  File "main.py", line 139, in main
  File "app\gazo.py", line 66, in from_replay_file
  File "app\objects\beatmap.py", line 114, in from_md5
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[5072] Failed to execute script 'main' due to unhandled exception!
[API] Getting data from kitsu /api/,

**Comment by elmolaygo** [comment]
this also happens with the latest

**Comment by xjunko** [comment]
You might want to update it since the older version doesn't have proper
fallback to the osu! api, that should fix it.

**Comment by xjunko** [comment]
@elmolaygo sorry for the late reply, life happened. 
would you happen to have that replay file still? 
i can't seem to reproduce this error somehow.
send it here, thanks!

**Comment by elmolaygo** [comment]
this is the replay file I used: https://buzzheavier.com/77ekc3yo26l7

**Comment by elmolaygo** [comment]
[Version] Current version: 0.8.3
[Version] Checking github for a new version of osr2png, success!
[Version] You're using the latest version of osr2png.
[Replay2Picture] File: `Alphi- - Kugimiya Rie. Horie Yui. Kitamura Eri - Orange [Taeyang's Insane] (2025-08-26) Osu.osr`
[Replay] Replay loaded!
[Replay2Picture] No Beatmap file passed, getting from osu!
[API] Trying to get beatmap id from get_id_from_md5_osu, [API] Failed to get beatmap id from osu! v1 api!
success!
[Replay2Picture] Calculating PP, done!
[API] Getting beatmap background from osu! /assets/, failed.
[API] Failed to get beatmap background, using the default one.
[API] Failed to get player id from osu! v1 api!
[Style::Akatsuki] Generating!
Traceback (most recent call last):
  File "main.py", line 173, in <module>
  File "main.py", line 159, in main
  File "app\gazo.py", line 55, in generate
  File "app\generation\canvas.py", line 76, in generate
  File "app\generation\styles\akatsuki\__init__.py", line 249, in generate
  File "app\generation\styles\akatsuki\__init__.py", line 228, in _generate_text
ZeroDivisionError: division by zero
[PYI-1860:ERROR] Failed to execute script 'main' due to unhandled exception!

Replay file used: https://pixeldrain.com/u/RNuyjy4e

now it's a different error 

I have Python 3.13 installed (idk maybe it's the wrong version)
